import { withBasePath } from '../utils/assets';

export const DEMO_CREDENTIALS = {
  admin: { username: 'admin_demo', password: 'Demo@123' },
  leader: { username: 'leader_demo', password: 'Demo@123' },
  user: { username: 'user_demo', password: 'Demo@123' },
};

export const DEMO_SEED = {
  settings: {
    name: 'KIM SƠN ECOSYSTEM',
    legalName: 'HỆ SINH THÁI Ô TÔ KIM SƠN (BẢN DEMO TĨNH)',
    foundingYear: 2014,
    headquarters: 'Thủ Đức, TP. Hồ Chí Minh',
    hotline: '0913 75 75 79',
    email: 'demo@kimsonauto.test',
    website: 'nguy3nantam.github.io/kimsonauto.com',
    slogan: 'Bản xem trước tĩnh dành cho khách hàng',
    totalEngineers: 300,
    totalCustomers: 50000,
    satisfactionRate: '99%',
    logo: withBasePath('/logo-kimson.png'),
    logoWhite: withBasePath('/logo-kimson-white.png'),
    favicon: withBasePath('/favicon.png'),
    siteTitle: 'Kim Sơn Automobiles - Demo Tĩnh',
  },
  users: [
    {
      id: '1',
      username: DEMO_CREDENTIALS.admin.username,
      password: DEMO_CREDENTIALS.admin.password,
      fullName: 'Ban Điều Hành Demo',
      name: 'Ban Điều Hành Demo',
      unit: 'VF GF Q2',
      department: 'Ban Giám Đốc',
      role: 'Admin',
      email: 'admin.demo@kimsonauto.test',
      phone: '0908 100 001',
      status: 'active',
      createdAt: '2026-09-01T08:00:00.000Z',
    },
    {
      id: '2',
      username: DEMO_CREDENTIALS.leader.username,
      password: DEMO_CREDENTIALS.leader.password,
      fullName: 'Leader Demo Biên Hòa',
      name: 'Leader Demo Biên Hòa',
      unit: 'VF Biên Hòa',
      department: 'Kinh Doanh',
      role: 'Leader',
      email: 'leader.demo@kimsonauto.test',
      phone: '0908 100 002',
      status: 'active',
      createdAt: '2026-09-05T08:30:00.000Z',
    },
    {
      id: '3',
      username: DEMO_CREDENTIALS.user.username,
      password: DEMO_CREDENTIALS.user.password,
      fullName: 'Nhân Viên Demo',
      name: 'Nhân Viên Demo',
      unit: 'VF Biên Hòa',
      department: 'Kinh Doanh',
      role: 'User',
      email: 'user.demo@kimsonauto.test',
      phone: '0908 100 003',
      status: 'active',
      createdAt: '2026-09-10T09:00:00.000Z',
    },
  ],
  pillars: [
    {
      id: 'distribution',
      title: 'Phân Phối Xe Điện & Xe Dịch Vụ',
      subtitle: 'Kim Sơn Auto Distribution',
      icon: 'Car',
      category: 'Thương Mại',
      badge: 'Trụ Cột 01',
      tagline: 'Tư vấn giải pháp phương tiện phù hợp cho khách hàng cá nhân và doanh nghiệp',
      summary: 'Mạng lưới showroom và tư vấn sản phẩm theo từng phân khúc sử dụng.',
      description: 'Bản demo mô phỏng cách Kim Sơn trình bày năng lực phân phối xe điện và xe dịch vụ.',
      capabilities: ['Tư vấn bán lẻ', 'Tư vấn đội xe doanh nghiệp', 'Hỗ trợ tài chính', 'Chăm sóc sau bán hàng'],
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=85&w=1200',
    },
    {
      id: 'engineering',
      title: 'Dịch Vụ Kỹ Thuật Chuyên Sâu',
      subtitle: 'Kim Sơn Service',
      icon: 'Wrench',
      category: 'Kỹ Thuật',
      badge: 'Trụ Cột 02',
      tagline: 'Bảo dưỡng, sửa chữa và chẩn đoán theo chuẩn xưởng hiện đại',
      summary: 'Đội ngũ kỹ thuật và quy trình tiếp nhận chuyên nghiệp.',
      description: 'Bản demo nhấn mạnh năng lực dịch vụ hậu mãi và vận hành xưởng.',
      capabilities: ['Bảo dưỡng định kỳ', 'Sửa chữa chuyên sâu', 'Đồng sơn', 'Cứu hộ kỹ thuật'],
      image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=85&w=1200',
    },
    {
      id: 'parts',
      title: 'Phụ Tùng & Linh Kiện',
      subtitle: 'Kim Sơn Genuine Parts',
      icon: 'Layers',
      category: 'Chuỗi Cung Ứng',
      badge: 'Trụ Cột 03',
      tagline: 'Đảm bảo nguồn cung ổn định cho toàn hệ sinh thái',
      summary: 'Danh mục phụ tùng và khả năng đáp ứng nhanh cho nhiều điểm dịch vụ.',
      description: 'Bản demo thể hiện vai trò của kho phụ tùng trong chuỗi vận hành.',
      capabilities: ['Kho phụ tùng trung tâm', 'Quản lý tồn kho', 'Phân phối liên chi nhánh', 'Phụ kiện chính hãng'],
      image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=85&w=1200',
    },
    {
      id: 'detailing',
      title: 'Chăm Sóc & Làm Đẹp Xe',
      subtitle: 'Kim Sơn Detailing',
      icon: 'Sparkles',
      category: 'Trải Nghiệm',
      badge: 'Trụ Cột 04',
      tagline: 'Nâng tầm trải nghiệm sở hữu xe cho khách hàng',
      summary: 'Các gói detailing, phủ bảo vệ và nâng cấp thẩm mỹ.',
      description: 'Bản demo minh họa dịch vụ giá trị gia tăng cho khách hàng sở hữu xe.',
      capabilities: ['Ceramic', 'PPF', 'Chăm sóc nội thất', 'Nâng cấp ngoại thất'],
      image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&q=85&w=1200',
    },
    {
      id: 'rescue',
      title: 'Cứu Hộ & Hỗ Trợ 24/7',
      subtitle: 'Kim Sơn Roadside Assistance',
      icon: 'ShieldAlert',
      category: 'An Toàn',
      badge: 'Trụ Cột 05',
      tagline: 'Đồng hành cùng khách hàng trên mọi hành trình',
      summary: 'Mô hình cứu hộ nhanh và điều phối hỗ trợ trên các trục giao thông chính.',
      description: 'Bản demo mô phỏng năng lực phản ứng nhanh và chăm sóc khẩn cấp.',
      capabilities: ['Tổng đài 24/7', 'Cứu hộ tại chỗ', 'Điều phối trạm gần nhất', 'Hỗ trợ đội xe'],
      image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=85&w=1200',
    },
  ],
  branches: [
    {
      id: 'bien-hoa',
      name: 'VinFast Biên Hòa',
      area: 'Đồng Nai',
      address: '643 Quốc Lộ 1, TP. Biên Hòa, Đồng Nai',
      hotline: '0913 75 75 79',
      email: 'bienhoa.demo@kimsonauto.test',
      role: 'Showroom & Trung Tâm Dịch Vụ',
      features: ['Showroom xe điện', 'Bảo dưỡng định kỳ', 'Xưởng kỹ thuật'],
    },
    {
      id: 'buu-long',
      name: 'VinFast Bửu Long',
      area: 'Đồng Nai',
      address: '1/1 Nguyễn Ái Quốc, TP. Biên Hòa, Đồng Nai',
      hotline: '0908 123 457',
      email: 'buulong.demo@kimsonauto.test',
      role: 'Trạm dịch vụ nhanh',
      features: ['Trưng bày xe', 'Bảo dưỡng nhanh', 'Chăm sóc xe'],
    },
    {
      id: 'long-thanh',
      name: 'VinFast Long Thành',
      area: 'Đồng Nai',
      address: 'Quốc Lộ 51, Huyện Long Thành, Đồng Nai',
      hotline: '0908 123 458',
      email: 'longthanh.demo@kimsonauto.test',
      role: 'Dịch vụ & cứu hộ khu vực',
      features: ['Tiếp nhận bảo dưỡng', 'Cứu hộ 24/7', 'Điểm hỗ trợ kỹ thuật'],
    },
    {
      id: 'binh-thanh',
      name: 'VinFast Bình Thạnh',
      area: 'TP. Hồ Chí Minh',
      address: 'Quốc Lộ 13, Bình Thạnh, TP. Hồ Chí Minh',
      hotline: '0908 123 459',
      email: 'binhthanh.demo@kimsonauto.test',
      role: 'Showroom trọng điểm',
      features: ['Showroom xe điện', 'Bảo dưỡng tiêu chuẩn', 'Cung ứng phụ tùng'],
    },
  ],
  news: [
    {
      id: '1',
      title: 'Kim Sơn ra mắt bản demo hệ sinh thái ô tô cho khách hàng trải nghiệm',
      category: 'Thông cáo báo chí',
      date: '25/09/2026',
      readTime: '4 phút đọc',
      image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=900',
      summary: 'Bản xem trước giúp khách hàng theo dõi cấu trúc hệ sinh thái, dịch vụ và mạng lưới vận hành.',
      content: 'Đây là bài viết mẫu trong chế độ demo tĩnh, dùng để trình bày giao diện và luồng nội dung cho khách hàng.',
      status: 'published',
    },
    {
      id: '2',
      title: 'Mạng lưới dịch vụ xe điện tiếp tục được mở rộng tại khu vực phía Nam',
      category: 'Phát triển bền vững',
      date: '20/09/2026',
      readTime: '5 phút đọc',
      image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=900',
      summary: 'Dữ liệu mẫu nhấn mạnh định hướng mở rộng mạng lưới và dịch vụ hậu mãi.',
      content: 'Nội dung mẫu phục vụ demo giao diện tin tức và trải nghiệm đọc bài viết.',
      status: 'published',
    },
    {
      id: '3',
      title: 'Hệ thống cứu hộ 24/7 được tích hợp trong bản trình diễn dịch vụ',
      category: 'Hạ tầng & cơ sở',
      date: '15/09/2026',
      readTime: '3 phút đọc',
      image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=900',
      summary: 'Minh họa năng lực điều phối dịch vụ và phản ứng nhanh trong hệ sinh thái.',
      content: 'Bài viết mẫu cho phép kiểm tra bố cục và điều hướng của trang tin tức.',
      status: 'published',
    },
  ],
  contacts: [
    {
      id: 'lead-1',
      name: 'Nguyễn Minh Demo',
      company: 'Doanh nghiệp vận tải mẫu',
      email: 'lead1@example.test',
      phone: '0912 300 001',
      service: 'Bảo dưỡng đội xe doanh nghiệp',
      branch: 'bien-hoa',
      message: 'Chúng tôi muốn tìm hiểu giải pháp bảo dưỡng định kỳ cho đội xe công ty.',
      status: 'pending',
      createdAt: '2026-09-25T14:30:00.000Z',
    },
    {
      id: 'lead-2',
      name: 'Trần Ngọc Demo',
      company: 'Đối tác phụ tùng mẫu',
      email: 'lead2@example.test',
      phone: '0912 300 002',
      service: 'Cung ứng phụ tùng',
      branch: 'binh-thanh',
      message: 'Xin tư vấn quy trình hợp tác phân phối phụ tùng chính hãng.',
      status: 'contacted',
      createdAt: '2026-09-24T09:15:00.000Z',
    },
  ],
  announcements: [
    {
      id: '1',
      title: 'Thông báo demo vận hành hệ sinh thái',
      content: 'Bản demo tĩnh cho phép khách hàng trải nghiệm giao diện và luồng quản trị cơ bản ngay trên GitHub Pages.',
      category: 'Vận hành',
      priority: 'urgent',
      targetUnit: 'Tất Cả Đơn Vị',
      targetDepartment: 'Tất Cả Bộ Phận',
      author: 'Ban Điều Hành Demo',
      createdAt: '2026-09-26T08:30:00.000Z',
      pinned: true,
    },
    {
      id: '2',
      title: 'Tài liệu giới thiệu năng lực dịch vụ đã được cập nhật',
      content: 'Khách hàng có thể xem trước bố cục cổng nội bộ, thông báo và file dùng chung trong chế độ không cần backend.',
      category: 'Kinh doanh',
      priority: 'high',
      targetUnit: 'Tất Cả Đơn Vị',
      targetDepartment: 'Marketing',
      author: 'Phòng Marketing Demo',
      createdAt: '2026-09-25T10:00:00.000Z',
      pinned: false,
    },
  ],
  sharedFiles: [
    {
      id: '1',
      name: 'Ho_so_gioi_thieu_nang_luc_demo.pdf',
      description: 'Tài liệu mẫu giới thiệu năng lực hệ sinh thái dành cho khách hàng xem trước.',
      category: 'Catalog & Bảng Giá',
      fileSize: '2.4 MB',
      fileType: 'PDF',
      targetDepartment: 'Kinh Doanh',
      uploadedBy: 'Phòng Marketing Demo',
      createdAt: '2026-09-25T11:00:00.000Z',
      downloads: 24,
    },
    {
      id: '2',
      name: 'Quy_trinh_tiep_nhan_khach_hang_demo.pdf',
      description: 'Mẫu tài liệu mô phỏng quy trình tiếp nhận khách hàng và điều phối dịch vụ.',
      category: 'Tài Liệu Kỹ Thuật',
      fileSize: '1.2 MB',
      fileType: 'PDF',
      targetDepartment: 'Dịch Vụ',
      uploadedBy: 'Ban Kỹ Thuật Demo',
      createdAt: '2026-09-24T15:20:00.000Z',
      downloads: 12,
    },
  ],
  sliders: [
    {
      id: '1',
      title: 'Kiến Tạo Chuỗi Giá Trị Hệ Sinh Thái Ô Tô',
      subtitle: 'BẢN DEMO TĨNH CHO KHÁCH HÀNG',
      description: 'Trải nghiệm giao diện giới thiệu hệ sinh thái Kim Sơn ngay trên GitHub Pages mà không cần backend chạy riêng.',
      image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=85&w=1920',
      primaryButtonText: 'Khám Phá Hệ Sinh Thái',
      primaryButtonLink: '/#nen-tang-phat-trien',
      secondaryButtonText: 'Xem Trang Quản Trị Demo',
      secondaryButtonLink: '/admin',
      order: 1,
      active: true,
      createdAt: '2026-09-26T00:00:00.000Z',
    },
    {
      id: '2',
      title: 'Mạng Lưới Showroom & Dịch Vụ Phía Nam',
      subtitle: 'TRÌNH DIỄN DỮ LIỆU CHI NHÁNH',
      description: 'Bản xem trước mô phỏng các điểm chạm khách hàng trong hệ sinh thái Kim Sơn.',
      image: withBasePath('/vinfast-kimson-bienhoa.jpg'),
      primaryButtonText: 'Xem Mạng Lưới',
      primaryButtonLink: '/mang-luoi',
      secondaryButtonText: 'Xem Tin Tức',
      secondaryButtonLink: '/tin-tuc',
      order: 2,
      active: true,
      createdAt: '2026-09-26T00:00:00.000Z',
    },
    {
      id: '3',
      title: 'Portal nội bộ hoạt động bằng dữ liệu cục bộ',
      subtitle: 'STATIC BACKEND DEMO',
      description: 'Đăng nhập bằng tài khoản demo để thử các luồng CRUD, thông báo, file dùng chung và tùy biến giao diện.',
      image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=85&w=1920',
      primaryButtonText: 'Đăng Nhập Demo',
      primaryButtonLink: '/admin',
      secondaryButtonText: 'Liên Hệ Tư Vấn',
      secondaryButtonLink: '/lien-he',
      order: 3,
      active: true,
      createdAt: '2026-09-26T00:00:00.000Z',
    },
  ],
};
